
src = Glob('src/*.cpp')
 
inc_path = ['inc']
 
defines = ['MODULE1_DEF']
ccflags = []
 
   
env = Environment () 
  
env.Append(CPPPATH=inc_path)
env.Append(CPPDEFINES=defines)
env.Append(CCCOMSTR="CC $SOURCES")
SharedLibrary('module1', Glob('src/*.cpp'))
 
obj = env.Object(src)
 
Return('obj')
